### ISSUE TITLE
请教一下 该怎么进行debug调试呢

### ISSUE THREAD

**Issue by 1369521908** [skywind3000/emake#19]
我跟着教程编写好了.mak文件 用命令行能成功构建出来文件
想知道下一步该怎么进行操作才能调试我的代码呢

**Comment by skywind3000** [comment]
调试当然是用 gdb 啊，你如果嫌弃 gdb 命令行不好用，可以找个 gdb 前端，比如 vscode 里面就有 gdb 的集成，还有其他选择：

- vim 里的 termdebug/vimspector 插件都可以对接 gdb 调试程序。
- cgdb ：另一个命令行比较好用的终端下的 gdb 前端。
- gdbgui：linux 下的 web 版本 gdb 前端。

**Comment by 1369521908** [comment]
感谢 不是专门写C/C++的 搞懂这些工具链都要花好多时间 所以有这些疑问
最后赞一下 确实好用
