### ISSUE TITLE
请问我再wlnk里面添加-Wl,-rpath参数为何会有错误呢

### ISSUE THREAD

**Issue by wahoro** [skywind3000/emake#2]

**Comment by wahoro** [comment]
额看了下源码知道了，原来是不需要再添加-Wl
直接写-rpath就行，3Q

**Comment by wahoro** [comment]
现在有另外一个问题，这个脚本没有办法在一个.mak里面生成所需要的lib和exe么，只能是一个文件对应生成一个exe或者lib?

**Comment by skywind3000** [comment]
对的，和vc的一个project一样，一个工程文件一个输出
