### ISSUE TITLE
很好的项目，一点建议

### ISSUE THREAD

**Issue by ghost** [skywind3000/emake#4]
能不能用flake8检查一下代码格式？代码是C风格的对python合适吗？

**Comment by skywind3000** [comment]
主体代码09年写的，不好意思，后来跑过flake8，一堆问题，不敢改了

**Comment by cclauss** [comment]
See #5 ...  The --select or --ignore options of flake8 are your friends.

**Comment by cclauss** [comment]
To work, flake8 must be turned on in https://travis-ci.org/skywind3000
