### ISSUE TITLE
Python的版本问题

### ISSUE THREAD

**Issue by zhang-stephen** [skywind3000/emake#7]
从知乎上过来，请问是否支持python 3？不太想单独为此搞一个python版本

**Comment by skywind3000** [comment]
不支持，写的太早了，要修改的话，工作量太大了

**Comment by skywind3000** [comment]
你可以安装一个 python 但是可执行不放入 $PATH 里，或者不是默认输入 python 启动那种，用全路径python 去执行它。

**Comment by zhang-stephen** [comment]
的确，问完这个问题我就想到了，于是用conda搞了一个虚拟环境，非常感谢您的回复
